[
    {
        "type": "message",
        "user": "U0KQ9QKH6",
        "text": "<@U1Y2R5C9L>  <@U1NC8D6V9> : I am assuming this is on the v0.6 branch. Your transaction times out in the case of an error. Rejection event support was developed in parallel with the rest of the events support and has not been fully integrated with transactional events. Loss of events is always going to be an issue so recovery from loss needs to be considered. Having said that, we are planning on looking at adding rejection event support to transactional events in v1.0.",
        "ts": "1478701817.000527"
    },
    {
        "type": "message",
        "user": "U13Q594J2",
        "text": "with latest code I couldn't bring my peer up (peer container is getting exited)  using the `docker_compose.yml` file specified in fabric-sdk-node here <https:\/\/raw.githubusercontent.com\/hyperledger\/fabric-sdk-node\/master\/test\/fixtures\/docker-compose.yml>",
        "edited": {
            "user": "U13Q594J2",
            "ts": "1478704362.000000"
        },
        "ts": "1478703535.000528"
    },
    {
        "type": "message",
        "user": "U13Q594J2",
        "text": "```14:52:05.613 [chaincode] Launch -&gt; DEBU 0b8 LaunchChaincode complete\n14:52:05.613 [sysccapi] RegisterSysCC -&gt; INFO 0b9 system chaincode %s(%s) registered vscc <http:\/\/github.com\/hyperledger\/fabric\/core\/system_chaincode\/vscc|github.com\/hyperledger\/fabric\/core\/system_chaincode\/vscc>\n14:52:05.613 [nodeCmd] serve -&gt; DEBU 0ba Running as validating peer - installing consensus \n14:52:05.613 [peer] initDiscovery -&gt; DEBU 0bb Retrieved discovery list from disk: []```\n*14:52:05.613 [nodeCmd] serve -&gt; CRIT 0bc Failed creating new peer with handler Security helper not provided*",
        "ts": "1478704141.000529"
    },
    {
        "type": "message",
        "user": "U13Q594J2",
        "text": "am I missing any thing here ?",
        "ts": "1478704164.000530"
    },
    {
        "type": "message",
        "user": "U13Q594J2",
        "text": "Seems there is an issue raised for this  <https:\/\/jira.hyperledger.org\/browse\/FAB-1037>",
        "ts": "1478704406.000532"
    },
    {
        "type": "message",
        "user": "U13TWBRBL",
        "text": "<@U13Q594J2> i also saw that earlier, you can work around it by changing the Peer\u2019s env variable CORE_SECURITY_ENABLED=false",
        "ts": "1478704490.000533"
    },
    {
        "type": "message",
        "user": "U13Q594J2",
        "text": "Thanks <@U13TWBRBL> , I will use this work around for now",
        "ts": "1478704538.000534"
    },
    {
        "type": "message",
        "user": "U13Q594J2",
        "text": "<@U13TWBRBL> I see this error and couldn't pass this error with latest code \n```\nnot ok 3 Error: Error: unknown service atomicbroadcast.AtomicBroadcast at ClientDuplexStream.&lt;anonymous&gt; (\/home\/ratnakar\/go\/src\/github.com\/hyperledger\/fabric-sdk-node\/lib\/Orderer.js:126:19) at emitOne (events.js:96:13) at ClientDuplexStream.emit (events.js:188:7) at ClientDuplexStream._emitStatusIfDone (\/home\/ratnakar\/go\/src\/github.com\/hyperledger\/fabric-sdk-node\/node_modules\/grpc\/src\/node\/src\/client.js:192:12) at ClientDuplexStream._receiveStatus (\/home\/ratnakar\/go\/src\/github.com\/hyperledger\/fabric-sdk-node\/node_modules\/grpc\/src\/node\/src\/client.js:169:8) at \/home\/ratnakar\/go\/src\/github.com\/hyperledger\/fabric-sdk-node\/node_modules\/grpc\/src\/node\/src\/client.js:634:14\n  ---\n    operator: fail\n  ...\n```",
        "ts": "1478705623.000535"
    },
    {
        "type": "message",
        "user": "U13TWBRBL",
        "text": "<@U13Q594J2> latest code is broken due to changes in orderer's protobuf: <https:\/\/jira.hyperledger.org\/browse\/FAB-1051>",
        "ts": "1478706628.000536"
    },
    {
        "type": "message",
        "user": "U13TWBRBL",
        "text": "if you want to try the latest node.js SDK code with fabric, grab this commit level in fabric:\n\ngit checkout -b sprint4 182a8672aaceacdbc3a9673d420a2c0bbcb5300c",
        "edited": {
            "user": "U13TWBRBL",
            "ts": "1478706749.000000"
        },
        "ts": "1478706732.000537"
    },
    {
        "type": "message",
        "user": "U13TWBRBL",
        "text": "then rebuild your images",
        "ts": "1478706736.000538"
    },
    {
        "type": "message",
        "user": "U13Q594J2",
        "text": "<@U13TWBRBL> Thankyou . Will try this one too :slightly_smiling_face:",
        "ts": "1478708556.000540"
    },
    {
        "type": "message",
        "user": "U18P24857",
        "text": "I ran V10 Node SDK end-to-end.js on non-vagrant env and see this message:",
        "ts": "1478716190.000541"
    },
    {
        "type": "message",
        "user": "U18P24857",
        "text": "vp0_1         | 23:31:53.347 [peer] ensureConnected -&gt; DEBU 1db Connected to: []\nvp0_1         | 23:31:53.347 [peer] ensureConnected -&gt; DEBU 1dc Discovery knows about: []\nvp0_1         | 23:31:54.922 [dockercontroller] deployImage -&gt; ERRO 1dd Error building images: The command '\/bin\/sh -c go install build-chaincode &amp;&amp; mv $GOPATH\/bin\/build-chaincode $GOPATH\/bin\/a8b45dca75f31d0164b13c1b614521fdd95638c3537e7b8ad7ef34510b6b836e' returned a non-zero code: 2\nvp0_1         | 23:31:54.922 [dockercontroller] deployImage -&gt; ERRO 1de Image Output:\nvp0_1         | ********************\nvp0_1         | Step 1 : FROM hyperledger\/fabric-ccenv\nvp0_1         |  ---&gt; f2f97222b33b\nvp0_1         | Step 2 : COPY . $GOPATH\/src\/build-chaincode\/\nvp0_1         |  ---&gt; 3c9140aa4e22\nvp0_1         | Removing intermediate container 03774ddf4bcf\nvp0_1         | Step 3 : WORKDIR $GOPATH\nvp0_1         |  ---&gt; Running in 1e03470eb477\nvp0_1         |  ---&gt; bc46c135a96f\nvp0_1         | Removing intermediate container 1e03470eb477\nvp0_1         | Step 4 : RUN go install build-chaincode &amp;&amp; mv $GOPATH\/bin\/build-chaincode $GOPATH\/bin\/a8b45dca75f31d0164b13c1b614521fdd95638c3537e7b8ad7ef34510b6b836e\nvp0_1         |  ---&gt; Running in 0caef0b73e42\nvp0_1         | # build-chaincode\nvp0_1         | src\/build-chaincode\/example_cc.go:33: stub.GetFunctionAndParameters undefined (type shim.ChaincodeStubInterface has no field or method GetFunctionAndParameters)\nvp0_1         | src\/build-chaincode\/example_cc.go:75: stub.GetFunctionAndParameters undefined (type shim.ChaincodeStubInterface has no field or method GetFunctionAndParameters)\nvp0_1         | src\/build-chaincode\/example_cc.go:206: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:\nvp0_1         |         *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)\nvp0_1         |                 have Init(shim.ChaincodeStubInterface) ([]byte, error)\nvp0_1         |                 want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)\nvp0_1         |\nvp0_1         | ********************",
        "ts": "1478716193.000542"
    },
    {
        "type": "message",
        "user": "U18P24857",
        "text": "does v10 Node SDK supoort non-vagrant env now?",
        "ts": "1478716219.000543"
    },
    {
        "type": "message",
        "user": "U18P24857",
        "text": "the commit level is 0edd927f49d6856cf5c792d527fce9bcf45ae050",
        "ts": "1478716236.000544"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "Thanks <@U0KQ9QKH6> I believe this is the SDK limitation not the server side issue?",
        "ts": "1478733232.000545"
    },
    {
        "type": "message",
        "user": "U1NC8D6V9",
        "text": "Thanks <@U0KQ9QKH6>",
        "ts": "1478734914.000546"
    },
    {
        "type": "message",
        "user": "U0KQ9QKH6",
        "text": "<@U1Y2R5C9L> : yes, its an sdk limitation at the moment",
        "ts": "1478740409.000547"
    },
    {
        "type": "message",
        "user": "U1Y2R5C9L",
        "text": "Thanks <@U0KQ9QKH6> ",
        "ts": "1478740434.000548"
    }
]