[
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "<@U0ZJZBJLF> unit tests under fabric\/gossip appear to be flaky\u2026 succeed\/fail randomly",
        "ts": "1477252377.000507"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "really? which one? got a link to a build that failed ?",
        "edited": {
            "user": "U0ZJZBJLF",
            "ts": "1477252549.000000"
        },
        "ts": "1477252418.000508"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "wait, how is that possible? nothing I sent in the last 2 weeks has been merged",
        "ts": "1477252460.000509"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "let me make sure I\u2019m not goofing up",
        "ts": "1477252580.000512"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "I do see gossip in master",
        "ts": "1477252648.000513"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "and tests under it",
        "ts": "1477252652.000514"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "it is there, but I'm asking- which test fails, or- which build fails",
        "edited": {
            "user": "U0ZJZBJLF",
            "ts": "1477252674.000000"
        },
        "ts": "1477252659.000515"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U0ULK2JPP|muralisr> uploaded a file: <https:\/\/hyperledgerproject.slack.com\/files\/muralisr\/F2T3AGK71\/pasted_image_at_2016_10_23_03_57_pm.png|Pasted image at 2016-10-23, 3:57 PM> and commented: for example",
        "file": {
            "id": "F2T3AGK71",
            "created": 1477252685,
            "timestamp": 1477252685,
            "name": "Pasted image at 2016_10_23 03_57 PM.png",
            "title": "Pasted image at 2016-10-23, 3:57 PM",
            "mimetype": "image\/png",
            "filetype": "png",
            "pretty_type": "PNG",
            "user": "U0ULK2JPP",
            "editable": false,
            "size": 39786,
            "mode": "hosted",
            "is_external": false,
            "external_type": "",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F2T3AGK71\/pasted_image_at_2016_10_23_03_57_pm.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "url_private_download": "https:\/\/files.slack.com\/files-pri\/T0J024XGA-F2T3AGK71\/download\/pasted_image_at_2016_10_23_03_57_pm.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_64": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F2T3AGK71-6bfba960b6\/pasted_image_at_2016_10_23_03_57_pm_64.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_80": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F2T3AGK71-6bfba960b6\/pasted_image_at_2016_10_23_03_57_pm_80.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_360": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F2T3AGK71-6bfba960b6\/pasted_image_at_2016_10_23_03_57_pm_360.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_360_w": 360,
            "thumb_360_h": 95,
            "thumb_480": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F2T3AGK71-6bfba960b6\/pasted_image_at_2016_10_23_03_57_pm_480.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_480_w": 480,
            "thumb_480_h": 127,
            "thumb_160": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F2T3AGK71-6bfba960b6\/pasted_image_at_2016_10_23_03_57_pm_160.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_720": "https:\/\/files.slack.com\/files-tmb\/T0J024XGA-F2T3AGK71-6bfba960b6\/pasted_image_at_2016_10_23_03_57_pm_720.png?t=xoxe-18002167554-139099126023-137701436192-e599afc92e",
            "thumb_720_w": 720,
            "thumb_720_h": 190,
            "image_exif_rotation": 1,
            "original_w": 872,
            "original_h": 230,
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/muralisr\/F2T3AGK71\/pasted_image_at_2016_10_23_03_57_pm.png",
            "permalink_public": "https:\/\/slack-files.com\/T0J024XGA-F2T3AGK71-d12b9cbf94",
            "channels": [
                "C27E2LGJY"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 1,
            "initial_comment": {
                "id": "Fc2T3BCJ81",
                "created": 1477252685,
                "timestamp": 1477252685,
                "user": "U0ULK2JPP",
                "is_intro": true,
                "comment": "for example",
                "channel": ""
            }
        },
        "user": "U0ULK2JPP",
        "upload": true,
        "display_as_bot": false,
        "username": "<@U0ULK2JPP|muralisr>",
        "bot_id": null,
        "ts": "1477252687.000517"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "rerunning go test under algo\/ made it pass",
        "ts": "1477252714.000518"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": ":open_mouth: impossible... why now? it is there for more than 2 weeks",
        "ts": "1477252730.000519"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": ":slightly_smiling_face:",
        "ts": "1477252743.000520"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "is it doing any non-local network activity ?",
        "ts": "1477252848.000521"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I think maybe the times need to be relaxed more. It's a tradeoff between not prolonging the tests and making the goroutine concurrency finish on time",
        "ts": "1477252859.000522"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "ie, going out of the box ?",
        "ts": "1477252865.000523"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "it's not, but it has many timers",
        "ts": "1477252872.000524"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "ok",
        "ts": "1477252890.000525"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I don't think I'll make it today, it's already 23:00 here but tomorrow I'll take a look at it. Can you send me in PM the link to the jenkins CI job that failed?",
        "ts": "1477252921.000526"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "absolitely",
        "ts": "1477252935.000527"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "sorry about that",
        "ts": "1477252940.000528"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "just thought I\u2019ll put it here for you to take a look when you can",
        "ts": "1477252958.000529"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "its not CI",
        "ts": "1477252967.000530"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "just my local unit-test",
        "ts": "1477252977.000531"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "np, sorry about failing the unit tests. I wonder why it happened now, it has been running for weeks and no one told me anything",
        "ts": "1477252977.000532"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "oh... wait, what go version are you using?",
        "ts": "1477252990.000533"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "go version\ngo version go1.6 linux\/amd64",
        "ts": "1477253017.000534"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "weird",
        "ts": "1477253025.000535"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "under vagrant",
        "ts": "1477253029.000536"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "don\u2019t worry about it",
        "ts": "1477253031.000537"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "nevermind then. I'll take a look and relax the times, send me the picture in PM please",
        "ts": "1477253041.000538"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "I ran a few times just now and didn\u2019t fail",
        "ts": "1477253045.000539"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "let\u2019s just keep an eye",
        "ts": "1477253051.000540"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "I need to fix this package anyway, there is a bug there. I delayed the fix to after the merge",
        "ts": "1477253063.000541"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "ok",
        "ts": "1477253068.000542"
    },
    {
        "user": "U2BF87970",
        "text": "<@U2BF87970|sumitks> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1477289756.000543"
    },
    {
        "type": "message",
        "user": "U2BF87970",
        "text": "hi I am getting the following error while running the command to start the peer node. error: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = \"transport: dial tcp 127.0.0.1:5005: getsockopt: connection refused\"; Reconnecting to {\"127.0.0.1:5005\" &lt;nil&gt;}\nCan anybody help me out.",
        "ts": "1477289769.000544"
    }
]