[
    {
        "type": "message",
        "user": "U11G06X52",
        "text": "peer client test fails with:   Dec 28, 2016 12:31:39 PM io.grpc.internal.ManagedChannelImpl &lt;init&gt;\nINFO: [ManagedChannelImpl@39aeed2f] Created with target ubuntu:7054\nDec 28, 2016 12:31:39 PM io.grpc.internal.ManagedChannelImpl &lt;init&gt;\nINFO: [ManagedChannelImpl@55d56113] Created with target ubuntu:7054\nDec 28, 2016 12:31:39 PM io.grpc.internal.ManagedChannelImpl &lt;init&gt;\nINFO: [ManagedChannelImpl@6e1ec318] Created with target ubuntu:7054\nDec 28, 2016 12:31:39 PM io.grpc.internal.ManagedChannelImpl &lt;init&gt;\nINFO: [ManagedChannelImpl@617faa95] Created with target ubuntu:7054\nDec 28, 2016 12:31:39 PM io.grpc.internal.ManagedChannelImpl &lt;init&gt;\nINFO: [ManagedChannelImpl@6366ebe0] Created with target ubuntu:7051\norg.hyperledger.fabric.sdk.exception.NoAvailableTCertException: Failed getting a new TCert\n\tat org.hyperledger.fabric.sdk.transaction.TransactionContext.deploy(TransactionContext.java:142)\n\tat org.hyperledger.fabric.sdk.Member.deploy(Member.java:252)\n\tat org.hyperledger.fabric.sdk.PeerClientTest.deploy(PeerClientTest.java:53)\n\tat org.hyperledger.fabric.sdk.PeerClientTest.setupChain(PeerClientTest.java:36)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n\tat org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)\n\tat org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)",
        "ts": "1482946396.000166"
    },
    {
        "type": "message",
        "user": "U11G06X52",
        "text": "I get this in CA log turning debug on:",
        "ts": "1482946558.000167"
    },
    {
        "type": "message",
        "user": "U11G06X52",
        "text": "09:31:40.407 [ca] readCertificateByKeyUsage -&gt; DEBU 32d Reading certificate for User1 and usage 1\n09:31:40.407 [ca] readCertificateByKeyUsage -&gt; DEBU 32e readCertificateByKeyUsage() Error: sql: no rows in result set",
        "ts": "1482946563.000168"
    }
]