[
    {
        "type": "message",
        "user": "U2AS0GVSP",
        "text": "it is not local, its a server that we are using for dev",
        "attachments": [
            {
                "fallback": "[October 22nd, 2016 7:42 PM] yacovm: where are you deploying to? maybe its a far away server? is the docker endpoint running locally or in a different host?",
                "ts": "1477161721.003169",
                "author_subname": "yacovm",
                "channel_id": "C0Y4PEU22",
                "channel_name": "fabric",
                "is_msg_unfurl": true,
                "text": "where are you deploying to? maybe its a far away server? is the docker endpoint running locally or in a different host?",
                "author_name": "Yacov Manevich",
                "author_link": "https:\/\/hyperledgerproject.slack.com\/team\/yacovm",
                "author_icon": "https:\/\/avatars.slack-edge.com\/2016-09-30\/85916865123_74ecb5d18535acea44aa_48.png",
                "mrkdwn_in": [
                    "text"
                ],
                "color": "D0D0D0",
                "from_url": "https:\/\/hyperledgerproject.slack.com\/archives\/fabric\/p1477161721003169",
                "is_share": true,
                "footer": "Posted in #fabric"
            }
        ],
        "ts": "1477216300.003178"
    },
    {
        "type": "message",
        "user": "U0ZJZBJLF",
        "text": "so maybe the communication to it is slow or something?",
        "ts": "1477216408.003181"
    },
    {
        "user": "U2T0NG04B",
        "text": "<@U2T0NG04B|leon.chu> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1477240862.003184"
    },
    {
        "type": "message",
        "user": "U1F5KATGX",
        "text": "hi, am setting up the dev environment on my windows 7 machine. am getting the below error while cloning the hyperledger fabric code.   I did create the key gen pair using puttygen and placed it in my local .ssh folder. Plz let me know if you have experienced this issue .                                                                                                                                                                                                          Permission denied (publickey).\nfatal: Could not read from remote repository.",
        "ts": "1477283990.003189"
    },
    {
        "type": "message",
        "user": "U0UHG4VP1",
        "text": "Did you add your public key to Gerrit?",
        "ts": "1477285855.003190"
    },
    {
        "type": "message",
        "user": "U1F5KATGX",
        "text": "<@U0UHG4VP1> , yes I did add public key to gerrit",
        "ts": "1477286768.003191"
    }
]