[
    {
        "type": "message",
        "user": "U11QC59MY",
        "text": "Is there a limit to number of nodes participating in a network(both development and production)? If yes, how many?",
        "edited": {
            "user": "U11QC59MY",
            "ts": "1484640204.000000"
        },
        "ts": "1484640188.001861"
    },
    {
        "user": "U3RM1BDS4",
        "text": "<@U3RM1BDS4|billykwok> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484642591.001863"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "question: where can i find information about functions in hfc sdk",
        "ts": "1484644116.001864"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "so to say an api description",
        "ts": "1484644134.001865"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "afaik in the official nodejs repository many links do not work anymore",
        "ts": "1484644157.001866"
    },
    {
        "type": "message",
        "user": "U195M30MD",
        "text": "what\u2019s the advantage of writing into the state instead of storing a map in the chaincode itself?",
        "ts": "1484644967.001867"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "it won\u2019t be in the blockchain if you store it in the chaincode",
        "ts": "1484645211.001868"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "found it it is in the doc folder :smile: :smile:",
        "ts": "1484645328.001869"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "when using hyperledger without security enabled i can deploy and invoke without referring to a special user",
        "ts": "1484648850.001870"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "is this also possible using hfc sdk",
        "ts": "1484648865.001871"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "so that i can use `deploy()` without having a user?",
        "ts": "1484648882.001872"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "so can i use hfc sdk without the membersrvc servcie",
        "ts": "1484649934.001875"
    },
    {
        "type": "message",
        "user": "U2D62LCQJ",
        "text": "is someone playing with Certs attributes?",
        "edited": {
            "user": "U2D62LCQJ",
            "ts": "1484654742.000000"
        },
        "ts": "1484654622.001876"
    },
    {
        "type": "message",
        "user": "U2D62LCQJ",
        "text": "cause i'm seeing this <https:\/\/github.com\/hyperledger\/fabric\/blob\/master\/docs\/API\/AttributesUsage.md>",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "hyperledger\/fabric",
                "title_link": "https:\/\/github.com\/hyperledger\/fabric\/blob\/master\/docs\/API\/AttributesUsage.md",
                "text": "Read-only mirror of <https:\/\/gerrit.hyperledger.org\/r\/#\/admin\/projects\/fabric>",
                "fallback": "GitHub: hyperledger\/fabric",
                "thumb_url": "https:\/\/avatars3.githubusercontent.com\/u\/7657900?v=3&s=400",
                "from_url": "https:\/\/github.com\/hyperledger\/fabric\/blob\/master\/docs\/API\/AttributesUsage.md",
                "thumb_width": 142,
                "thumb_height": 142,
                "service_icon": "https:\/\/github.com\/apple-touch-icon.png",
                "id": 1
            }
        ],
        "ts": "1484654638.001877"
    },
    {
        "type": "message",
        "user": "U2D62LCQJ",
        "text": "and the firsts questions i have are, \n\n1. it says the attributes are validated by the ACA, but then on the example are sended on the json? are still validated againts the ACA? if they are different are them discarded? I suppose the attributes should be stored on the yaml of the memberserv along with the enrollID\/secret, right?\n\n2. can i use them to gather the identity of the invoker of the chaincode to have access control instead of based on atributtes based on identity?",
        "edited": {
            "user": "U2D62LCQJ",
            "ts": "1484654920.000000"
        },
        "ts": "1484654904.001880"
    },
    {
        "type": "message",
        "user": "U1B9E51R8",
        "text": "Hi all, I want to update my chaincode from v0.5 to v0.6, how can I migrate data(blocks, state) ? Is there any best practice or existing tool to do that?",
        "ts": "1484656182.001882"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "<@U2D62LCQJ> you can get identity in chaincode (caller cert) by calling stub.getCallerCertificate()",
        "ts": "1484656478.001883"
    },
    {
        "type": "message",
        "user": "U2D62LCQJ",
        "text": "but does change through calls right?",
        "ts": "1484656523.001884"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "if you use tcerts",
        "ts": "1484656533.001885"
    },
    {
        "type": "message",
        "user": "U2D62LCQJ",
        "text": "and how to change to ecerts?",
        "ts": "1484656551.001886"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "just sign it with ecert",
        "ts": "1484656581.001887"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "but ecert will not have attributes",
        "ts": "1484656612.001888"
    },
    {
        "type": "message",
        "user": "U2D62LCQJ",
        "text": "ok thanks!",
        "ts": "1484656656.001889"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "<https:\/\/hyperledger-fabric.readthedocs.io\/en\/latest\/tech\/attributes\/>",
        "ts": "1484656680.001890"
    },
    {
        "type": "message",
        "user": "U2D62LCQJ",
        "text": "yeah, i've already read all those",
        "ts": "1484656782.001891"
    },
    {
        "user": "U3LMVC4Q4",
        "text": "<@U3LMVC4Q4|mtnieto> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484656837.001892"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "<@U0KPFAZNF> `can\/should the client\/SDK ensure that either all or \"enough\" endorsers derived the same RWS` .. absolutely, yes.",
        "ts": "1484657865.001893"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "in other words, the responses should be identical",
        "ts": "1484657890.001894"
    },
    {
        "type": "message",
        "user": "U0ULK2JPP",
        "text": "and endorsed",
        "ts": "1484657896.001895"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": ":+1:",
        "ts": "1484657950.001896"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "hey guys im trying to deploy a chaincode using hfc sdk",
        "ts": "1484661172.001897"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "this is the error im getting",
        "ts": "1484661177.001898"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "`request = {\"fcn\":\"init\",\"args\":[\"50\",\"300\"],\"chaincodePath\":\"settlement\/\"}\n error = {\"error\":{\"code\":2,\"metadata\":{\"_internal_repr\":{}}},\"msg\":\"Error: sql: no rows in result set\"}\n`",
        "ts": "1484661186.001899"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "can anyone help me, what am i doing wrong",
        "ts": "1484661224.001900"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "i try to deploy with the following function",
        "ts": "1484661268.001901"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "`function deploychaincode(err, deployuser) {\n\n\tvar deployRequest = {\n\t\tfcn: \"init\",\n\t\targs: [\"50\", \"300\"],\n\t\tchaincodePath: \"settlement\/\"\n\t};\n\n\tvar deployTx = deployuser.deploy(deployRequest);\n\n\tdeployTx.on(\"complete\", function(results){\n\t\tchaincodeID = results.chaincodeID;\n\t\tconsole.log(\"\\nChaincode ID: \" + chaincodeID);\n\t\tconsole.log(util.format(\"\\n Successfully deployed chaincode\\nrequest = %j\\n response = %j\", deployRequest, results));\n\t\tfs.writeFileSync(chaincodeIDPath, chaincodeID);\n\t});\n\n\tdeployTx.on(\"error\", function(err) {\n\t\tconsole.log(util.format(\"\\nFailed to deploy chaincode\\nrequest = %j\\n error = %j\", deployRequest, err));\n\t});\n}`",
        "ts": "1484661288.001902"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "are you able to deploy your chaincode over console?",
        "ts": "1484661442.001903"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "yes",
        "ts": "1484661448.001904"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "i think it has to do with my deploy request",
        "ts": "1484661483.001905"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "is chaincodepath  absolute or relative or dependent on go path ?",
        "ts": "1484661501.001906"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "it should be relative to gopath",
        "ts": "1484661511.001907"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "do i need chaincodeid  or chaincodename?",
        "ts": "1484661529.001908"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "I think it should be generated",
        "ts": "1484661553.001909"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "at least it\u2019s not in the example <https:\/\/github.com\/IBM-Blockchain\/SDK-Demo\/blob\/master\/helloblockchain.js>",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "IBM-Blockchain\/SDK-Demo",
                "title_link": "https:\/\/github.com\/IBM-Blockchain\/SDK-Demo\/blob\/master\/helloblockchain.js",
                "text": "SDK-Demo - Sample Node.js program to demonstrate the HFC SDK APIs interacting with Starter and High Security Bluemix networks",
                "fallback": "GitHub: IBM-Blockchain\/SDK-Demo",
                "thumb_url": "https:\/\/avatars2.githubusercontent.com\/u\/17178768?v=3&s=400",
                "from_url": "https:\/\/github.com\/IBM-Blockchain\/SDK-Demo\/blob\/master\/helloblockchain.js",
                "thumb_width": 200,
                "thumb_height": 200,
                "service_icon": "https:\/\/github.com\/apple-touch-icon.png",
                "id": 1
            }
        ],
        "ts": "1484661568.001910"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "do i need certificatepath even when security is off ?",
        "ts": "1484661587.001912"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "yeah thats exactly what im looking at",
        "ts": "1484661598.001913"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "I think it must be more or less the same parameters you use in console",
        "ts": "1484661640.001914"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "hmm how do i find out what this error means?",
        "ts": "1484661770.001915"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "you see any errors at peer?",
        "ts": "1484661840.001916"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "no unfortunately not",
        "ts": "1484661906.001917"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "just a guess: maybe the hfc incorrectly interprets the empty result from your chaincode init function",
        "ts": "1484662443.001918"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "try returning something there other than nil",
        "ts": "1484662456.001919"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "ok ill try that",
        "ts": "1484662645.001920"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "hmm unfortunately it does not work",
        "ts": "1484663171.001921"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "however i can successfully enroll and register users",
        "ts": "1484663193.001922"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "`test`",
        "ts": "1484663280.001923"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "is the deploy request",
        "ts": "1484663342.001924"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "var deployRequest = {\n\t\tfcn: \"init\",\n\t\targs: [\"50\", \"300\"],\n\t\tchaincodePath: \"settlement\"\n\t};",
        "ts": "1484663352.001925"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "is it correct or am i missing something",
        "ts": "1484663361.001926"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "this is the equivalent",
        "ts": "1484663393.001927"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "`peer chaincode deploy -c '{\"Args\": [\"init\",\"20\", \"30\"]}' -p settlement`",
        "ts": "1484663402.001928"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "and it works",
        "ts": "1484663411.001929"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "i think that it has to do with my hfc version",
        "ts": "1484663968.001930"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "i remember having problems with this hfc interface before",
        "ts": "1484663983.001931"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "so im using hyperledger v0.6",
        "ts": "1484663991.001932"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "which hfc version do you recommend for this?",
        "ts": "1484663999.001933"
    },
    {
        "type": "message",
        "user": "U3S1PENVA",
        "text": "you have this one? <https:\/\/www.npmjs.com\/package\/hfc>",
        "ts": "1484664294.001934"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "yeah and tested in all available versions",
        "ts": "1484664515.001935"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "but i found something...",
        "ts": "1484664520.001936"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "although im not using bluemix",
        "ts": "1484664550.001937"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "<https:\/\/github.com\/IBM-Blockchain\/ibm-blockchain-issues\/issues\/64>",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "Bluemix blockchain service deployment issue \u00b7 Issue #64 \u00b7 IBM-Blockchain\/ibm-blockchain-issues \u00b7 GitHub",
                "title_link": "https:\/\/github.com\/IBM-Blockchain\/ibm-blockchain-issues\/issues\/64",
                "text": "Hi all, I got recently issues deploying to a Bluemix Blockchain service. Most of the times I run my code (attached) I got the following: hfc Failed getting a new TCert [Error] +695ms error: [SDK]...",
                "fallback": "GitHub: Bluemix blockchain service deployment issue \u00b7 Issue #64 \u00b7 IBM-Blockchain\/ibm-blockchain-issues",
                "thumb_url": "https:\/\/avatars1.githubusercontent.com\/u\/14276211?v=3&s=400",
                "from_url": "https:\/\/github.com\/IBM-Blockchain\/ibm-blockchain-issues\/issues\/64",
                "thumb_width": 420,
                "thumb_height": 420,
                "service_icon": "https:\/\/a.slack-edge.com\/bfaba\/img\/unfurl_icons\/github.png",
                "id": 1
            }
        ],
        "ts": "1484664586.001938"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "this seems to be the same or at least a similar problem",
        "ts": "1484664645.001940"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "maybe some uber dev-pros can help me here",
        "ts": "1484664659.001941"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "so first question would be, when deploying via hfc sdk do i have to include the `certificatePath` ?",
        "ts": "1484665614.001942"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "when security is turned off",
        "ts": "1484665621.001943"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "i think not",
        "ts": "1484667095.001944"
    },
    {
        "type": "message",
        "user": "U1JAPLQSY",
        "text": "@channe",
        "ts": "1484667676.001945"
    },
    {
        "user": "U1B6WUMMZ",
        "text": "<@U1B6WUMMZ|alihendavi> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484669261.001948"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "got it working",
        "ts": "1484670357.001949"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "had to `rm \/tmp\/keyValStore\/member.admin`",
        "ts": "1484670468.001950"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "so new question",
        "ts": "1484671162.001951"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "which hfc version do you recommend for hyperledger v0.6 ?",
        "ts": "1484671174.001952"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "again question: when using hfc sdk for chaincode deployment i have the impression that it does not recognize my GOPATH",
        "ts": "1484672320.001953"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "however using `echo $GOPATH` shows me that it is set",
        "ts": "1484672344.001954"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "where do i have to set the GOPATH correctly for hfc sdk deploy chaincode to work?",
        "ts": "1484672373.001955"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "i think the problem is deployin chaincode in NON-dev mode using the hfc sdk",
        "ts": "1484673589.001956"
    },
    {
        "type": "message",
        "user": "U0PB67X4K",
        "text": "<@U3BSMKS21> - definitely use the latest version of hfc available via npm -  I think it's v0.6.5",
        "ts": "1484674372.001957"
    },
    {
        "type": "message",
        "user": "U0PB67X4K",
        "text": "it should recognize $GOPATH if its set.  You can try doing `DEBUG=hfc node [your_app.js]`",
        "ts": "1484674537.001958"
    },
    {
        "type": "message",
        "user": "U0PB67X4K",
        "text": "you can of course always just print the output of `process.env['GOPATH']` as well in your Node program which is using the SDK",
        "ts": "1484674590.001959"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "@garsingh thx",
        "ts": "1484674949.001960"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "<@U0PB67X4K>  to be specific i have the following problem",
        "ts": "1484674968.001961"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "18:39:31.092 [dockercontroller] deployImage -&gt; ERRO 017 Error building images: The command '\/bin\/sh -c go install build-chaincode &amp;&amp; cp src\/build-chaincode\/vendor\/github.com\/hyperledger\/fabric\/peer\/core.yaml $GOPATH\/bin &amp;&amp; mv $GOPATH\/bin\/build-chaincode $GOPATH\/bin\/b3ca6d9fd3c431e6e0744bd3d1500db858c7a5cb60499883c0e95165c9a879de' returned a non-zero code: 1\n18:39:31.092 [dockercontroller] deployImage -&gt; ERRO 018 Image Output:\n********************\nStep 1 : FROM hyperledger\/fabric-baseimage\n ---&gt; 778b7e6e8b67\nStep 2 : COPY . $GOPATH\/src\/build-chaincode\/\n ---&gt; Using cache\n ---&gt; f24fd59fa43d\nStep 3 : WORKDIR $GOPATH\n ---&gt; Using cache\n ---&gt; 12c214b6b129\nStep 4 : RUN go install build-chaincode &amp;&amp; cp src\/build-chaincode\/vendor\/github.com\/hyperledger\/fabric\/peer\/core.yaml $GOPATH\/bin &amp;&amp; mv $GOPATH\/bin\/build-chaincode $GOPATH\/bin\/b3ca6d9fd3c431e6e0744bd3d1500db858c7a5cb60499883c0e95165c9a879de\n ---&gt; Running in b2f18b58d422\nsrc\/build-chaincode\/settlement.go:10:2: cannot find package \"<http:\/\/github.com\/hyperledger\/fabric\/core\/chaincode\/shim|github.com\/hyperledger\/fabric\/core\/chaincode\/shim>\" in any of:\n\t\/opt\/go\/src\/github.com\/hyperledger\/fabric\/core\/chaincode\/shim (from $GOROOT)\n\t\/opt\/gopath\/src\/github.com\/hyperledger\/fabric\/core\/chaincode\/shim (from $GOPATH)\n\n********************\n18:39:31.665 [dockercontroller] deployImage -&gt; ERRO 019 Error building images: The command '\/bin\/sh -c go install build-chaincode &amp;&amp; cp src\/build-chaincode\/vendor\/github.com\/hyperledger\/fabric\/peer\/core.yaml $GOPATH\/bin &amp;&amp; mv $GOPATH\/bin\/build-chaincode $GOPATH\/bin\/b3ca6d9fd3c431e6e0744bd3d1500db858c7a5cb60499883c0e95165c9a879de' returned a non-zero code: 1\n18:39:31.665 [dockercontroller] deployImage -&gt; ERRO 01a Image Output:\n********************\nStep 1 : FROM hyperledger\/fabric-baseimage\n ---&gt; 778b7e6e8b67\nStep 2 : COPY . $GOPATH\/src\/build-chaincode\/\n ---&gt; Using cache\n ---&gt; f24fd59fa43d\nStep 3 : WORKDIR $GOPATH\n ---&gt; Using cache\n ---&gt; 12c214b6b129\nStep 4 : RUN go install build-chaincode &amp;&amp; cp src\/build-chaincode\/vendor\/github.com\/hyperledger\/fabric\/peer\/core.yaml $GOPATH\/bin &amp;&amp; mv $GOPATH\/bin\/build-chaincode $GOPATH\/bin\/b3ca6d9fd3c431e6e0744bd3d1500db858c7a5cb60499883c0e95165c9a879de\n ---&gt; Running in 046be90110d3\nsrc\/build-chaincode\/settlement.go:10:2: cannot find package \"<http:\/\/github.com\/hyperledger\/fabric\/core\/chaincode\/shim|github.com\/hyperledger\/fabric\/core\/chaincode\/shim>\" in any of:\n\t\/opt\/go\/src\/github.com\/hyperledger\/fabric\/core\/chaincode\/shim (from $GOROOT)\n\t\/opt\/gopath\/src\/github.com\/hyperledger\/fabric\/core\/chaincode\/shim (from $GOPATH)\n\n********************\n18:39:31.665 [chaincode] Launch -&gt; ERRO 01b launchAndWaitForRegister failed Error starting container: The command '\/bin\/sh -c go install build-chaincode &amp;&amp; cp src\/build-chaincode\/vendor\/github.com\/hyperledger\/fabric\/peer\/core.yaml $GOPATH\/bin &amp;&amp; mv $GOPATH\/bin\/build-chaincode $GOPATH\/bin\/b3ca6d9fd3c431e6e0744bd3d1500db858c7a5cb60499883c0e95165c9a879de' returned a non-zero code: 1",
        "ts": "1484675005.001962"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "this is what i get when i try to deploy using hfc sdk",
        "ts": "1484675052.001963"
    },
    {
        "type": "message",
        "user": "U0PB67X4K",
        "text": "did you vendor the fabric source within your chaincode project?",
        "ts": "1484675097.001964"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "no sry, im feeling like an uber noob now :smile:",
        "ts": "1484675123.001965"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "could you explain what it is and why i do not have to do it when deploying via CLI",
        "ts": "1484675147.001966"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "ok found something that explains it",
        "ts": "1484675973.001967"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "so what is the reason behind it ?",
        "ts": "1484675982.001968"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "<@U3BSMKS21> well, it is a long story;-)",
        "ts": "1484676798.001969"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "it has to do with the lifecycle of the creation for the chaincode's docker image",
        "ts": "1484676895.001970"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "if you deploy via the cli, then the binary has that context (the chaincode shim package in particular",
        "ts": "1484676919.001971"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "when you deploy with the sdk or REST API, then you need to ship all the bits",
        "ts": "1484676991.001972"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "frankly I would have preferred a model where we build a docker image and just point to a published docker registry entry",
        "ts": "1484677032.001973"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "of course then you need to deal with platform and architecture specific issues",
        "ts": "1484677100.001974"
    },
    {
        "type": "message",
        "user": "U3BSMKS21",
        "text": "thx for the nice explanation",
        "ts": "1484677166.001975"
    },
    {
        "type": "message",
        "user": "U1P56CWF5",
        "text": "<@U0ULK2JPP> to your response on whether SDK validates the endorsements, does it mean that the transaction is considered Endorsed if and only if \"enough\" number of endorsements are received *and* all the received endorsements match? If so the description in the 1.0 proposal should be updated to include both the criteria.",
        "ts": "1484679062.001976"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U0KM61BCP> <@U3BSMKS21> I should also add, I think we can do better and I have ideas\/plans on how",
        "ts": "1484681674.001977"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "But that is how it is today",
        "ts": "1484681688.001978"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "rhymes with main pool?",
        "ts": "1484682563.001979"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "<@U0KPFAZNF> ^^",
        "ts": "1484682572.001980"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "Heh, yes, though even outside of chaintool I think we can improve",
        "ts": "1484682605.001981"
    },
    {
        "type": "message",
        "user": "U0KM61BCP",
        "text": "agree",
        "ts": "1484682610.001982"
    },
    {
        "user": "U34TJFSCB",
        "text": "<@U34TJFSCB|shaggy_kp> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484708237.001983"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "I was running a fabric network locally using docker.  I was attempting to delete my blockchain for testing purposes by navigating to the validating peer file system by using a command like docker exec -it substitute_container_name bash and deleting the \/var\/hyperledger\/production directory.  I initially deleted \/var\/hyperledger\/production\/db but I was still seeing my blockchain so deleted the \/var\/hyperledger\/production directory.  Now I can't startup my network, memberservices container starts up by the fabric peer does not.  I get the below error:",
        "ts": "1484708715.001984"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "vp0_1         | 02:40:56.233 [crypto] Debugf -&gt; DEBU 028 [validator.my_vp0] Storing TCA certificate for [my_vp0]...\nvp0_1         | 02:40:56.233 [crypto] Debug -&gt; DEBU 029 [validator.my_vp0]  Getting ECA client...\nvp0_1         | 02:40:56.234 [crypto] Debugf -&gt; DEBU 02a [validator.my_vp0] Dial to addr:[membersrvc:7054], with serverName:[tlsca]...\nvp0_1         | 02:40:56.235 [crypto] Debug -&gt; DEBU 02b [validator.my_vp0]  TLS disabled...\nvp0_1         | 02:40:56.236 [crypto] Debug -&gt; DEBU 02c [validator.my_vp0]  Getting ECA client...done\nvp0_1         | 02:40:56.262 [crypto] Errorf -&gt; ERRO 02d [validator.my_vp0] Failed invoking CreateCertficatePair [rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set].\nvp0_1         | 02:40:56.263 [crypto] Errorf -&gt; ERRO 02e [validator.my_vp0] Failed getting enrollment certificate [id=my_vp0]: [rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set]\nvp0_1         | 02:40:56.263 [crypto] Errorf -&gt; ERRO 02f [validator.my_vp0] Failed retrieving enrollment data [rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set].\nvp0_1         | 02:40:56.264 [crypto] Errorf -&gt; ERRO 030 [validator.my_vp0] Failed registering node crypto engine [rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set].\nvp0_1         | 02:40:56.264 [crypto] Errorf -&gt; ERRO 031 [validator.my_vp0] Failed registering peer [my_vp0]: [rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set]\nvp0_1         | 02:40:56.265 [crypto] Errorf -&gt; ERRO 032 [validator.my_vp0] Failed registering [my_vp0]: [rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set]\nvp0_1         | 02:40:56.265 [crypto] RegisterValidator -&gt; ERRO 033 Failed registering validator [my_vp0] with name [my_vp0] [rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set].\nvp0_1         | Error: rpc error: code = 2 desc = Identity lookup error: sql: no rows in result set\nvp0_1         | Usage:\nvp0_1         |   peer node start [flags]\nvp0_1         | \nvp0_1         | Flags:\nvp0_1         |       --peer-chaincodedev   Whether peer in chaincode development mode\nvp0_1         | \nvp0_1         | Global Flags:\nvp0_1         |       --logging-level string       Default logging level and overrides, see core.yaml for full syntax\nvp0_1         |       --test.coverprofile string   Done (default \"coverage.cov\")\nvp0_1         |   -v, --version                    Display current version of fabric peer server\nvp0_1         | \nshaggykp_vp0_1 exited with code 1",
        "ts": "1484708718.001985"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "How do I fix this?",
        "ts": "1484708753.001986"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U34TJFSCB> I am not sure what is actually failing, but I suspect the persistence is caused by your composition",
        "ts": "1484709197.001987"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "try running \"docker-compose down\" (using any \"-f\" directives that are mirrorred from your \"up\")",
        "ts": "1484709227.001988"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "and then try again: that should start you fresh",
        "ts": "1484709234.001989"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "note that you are blowing away the old containers though",
        "ts": "1484709248.001990"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U0KM61BCP> do we have an archive of any of the old GH issues?",
        "ts": "1484709290.001991"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "I had written an issue (I believe it predated the JIRA migration)",
        "ts": "1484709313.001992"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "<@U0KPFAZNF> I tried running \"docker-compose down\" but this resulted in the same error.",
        "ts": "1484710005.001993"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "are you specifying any volume mounts in your composition?",
        "ts": "1484710051.001994"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "I don't think so.   Actually, the errors are not exactly the same.  Below is what I get now:",
        "ts": "1484710179.001995"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "vp0_1         | 03:25:06.119 [crypto] Errorf -&gt; ERRO 021 [validator.my_vp0] Failed requesting read certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\nvp0_1         | 03:25:06.119 [crypto] Errorf -&gt; ERRO 022 [validator.my_vp0] Failed requesting ECA certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\nvp0_1         | 03:25:06.119 [crypto] Errorf -&gt; ERRO 023 [validator.my_vp0] Failed getting ECA certificate [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\nvp0_1         | 03:25:06.119 [crypto] Errorf -&gt; ERRO 024 [validator.my_vp0] Failed retrieving ECA certs chain [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\nvp0_1         | 03:25:06.119 [crypto] Errorf -&gt; ERRO 025 [validator.my_vp0] Failed registering node crypto engine [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\nvp0_1         | 03:25:06.119 [crypto] Errorf -&gt; ERRO 026 [validator.my_vp0] Failed registering peer [my_vp0]: [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure]\nvp0_1         | 03:25:06.120 [crypto] Errorf -&gt; ERRO 027 [validator.my_vp0] Failed registering [my_vp0]: [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure]\nvp0_1         | 03:25:06.120 [crypto] RegisterValidator -&gt; ERRO 028 Failed registering validator [my_vp0] with name [my_vp0] [rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure].\nvp0_1         | Error: rpc error: code = 14 desc = grpc: RPC failed fast due to transport failure\nvp0_1         | 2017\/01\/18 03:25:06 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = \"transport: dial tcp 172.17.0.2:7054: getsockopt: connection refused\"; Reconnecting to {\"membersrvc:7054\" &lt;nil&gt;}",
        "ts": "1484710181.001996"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "is this v0.6 or master?",
        "ts": "1484710213.001997"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "The hyperledger\/fabric-peer is latest",
        "ts": "1484710335.001998"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "but the hyperledger I cloned is v0.6",
        "ts": "1484710366.001999"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "I was able to at least get my network up and running again by changing the ports listing in my docker-compose.yml.  It was listing 7050, 7051, and 7053.  I changed it to 7051,7052,7053.",
        "ts": "1484711975.002000"
    },
    {
        "type": "message",
        "user": "U34TJFSCB",
        "text": "I don't understand why listing port 7050 doesn't work",
        "ts": "1484712037.002001"
    },
    {
        "user": "U31A496G2",
        "text": "<@U31A496G2|arnabkaycee> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484714536.002002"
    },
    {
        "user": "U38DC9CCF",
        "text": "<@U38DC9CCF|yedendra> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484716940.002003"
    },
    {
        "user": "U3S80ECAC",
        "text": "<@U3S80ECAC|ss6> has joined the channel",
        "type": "message",
        "subtype": "channel_join",
        "ts": "1484723792.002004"
    }
]