[
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "<@U0KPFAZNF> <@U0P2GSA8Z> After looking more at the issue I have when deploying the simple chaincode (<https:\/\/jira.hyperledger.org\/browse\/FAB-37>), I think one issue might be due to networking features of Docker on mac OS.",
        "ts": "1484322579.001030"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "<@U3MB5BH42> are you using docker-for-mac or docker-engine?",
        "ts": "1484322611.001031"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "I did not know there was a difference",
        "ts": "1484322637.001032"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "there is: the short answer is docker-for-mac is newer and the only one that will really work",
        "ts": "1484322659.001033"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "I downloaded it here: <https:\/\/www.docker.com\/products\/overview>",
        "attachments": [
            {
                "service_name": "Docker",
                "title": "Get Docker",
                "title_link": "https:\/\/www.docker.com\/products\/overview",
                "fallback": "Docker: Get Docker",
                "image_url": "https:\/\/www.docker.com\/sites\/default\/files\/social\/docker-twitter-share.png",
                "ts": 1453709371,
                "from_url": "https:\/\/www.docker.com\/products\/overview",
                "image_width": 625,
                "image_height": 250,
                "image_bytes": 49214,
                "service_icon": "https:\/\/www.docker.com\/favicons\/apple-touch-icon-57x57.png",
                "id": 1
            }
        ],
        "ts": "1484322668.001034"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "It's version 1.12.6",
        "ts": "1484322680.001036"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "do you have a little docker whale in the menu tray?",
        "ts": "1484322692.001037"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "yes",
        "ts": "1484322697.001038"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "or do you have to do \"docker-machine start\"",
        "ts": "1484322700.001039"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "ok, good, you probably have docker-for-mac then",
        "ts": "1484322707.001040"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "another possibility is you are getting bit by a bug I am tracking in our docker containers",
        "ts": "1484322742.001041"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "related to DNS",
        "ts": "1484322748.001042"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "But if I force the ip address to the peer",
        "ts": "1484322748.001043"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "at least deployment does not timeout",
        "ts": "1484322755.001044"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "but Invoke still does not work",
        "ts": "1484322760.001045"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "(I do that using PEER_CORE_ADDRESS=<http:\/\/xxx.xxx.xxx.xxx:7051|xxx.xxx.xxx.xxx:7051>)",
        "ts": "1484322777.001046"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "I think this is at least one issue",
        "ts": "1484322855.001047"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "as if I run chaincode_example02 outside the docker container",
        "ts": "1484322864.001048"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "even with default parameters (0.0.0.0:7051 for the peer address), then it connects correctly to the peer",
        "ts": "1484322892.001049"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "while inside docker",
        "ts": "1484322897.001050"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "docker logs indicated <https:\/\/gist.github.com\/fabrice102\/7dac151410cf4b35ca9b49679f14eb53>",
        "ts": "1484322924.001051"
    },
    {
        "type": "message",
        "subtype": "file_share",
        "text": "<@U3MB5BH42|fbenhamo> shared a file: <https:\/\/hyperledgerproject.slack.com\/files\/fbenhamo\/F3RD8M0FQ\/gistfile1_txt.txt|gistfile1.txt>",
        "file": {
            "id": "F3RD8M0FQ",
            "created": 1484239903,
            "timestamp": 1484239903,
            "name": "gistfile1_txt.txt",
            "title": "gistfile1.txt",
            "mimetype": "text\/plain",
            "filetype": "text",
            "pretty_type": "Plain Text",
            "user": "U3MB5BH42",
            "editable": true,
            "size": 1005,
            "mode": "snippet",
            "is_external": true,
            "external_type": "unknown",
            "is_public": true,
            "public_url_shared": false,
            "display_as_bot": false,
            "username": "",
            "url_private": "https:\/\/gist.github.com\/7dac151410cf4b35ca9b49679f14eb53#file-gistfile1-txt",
            "url_private_download": "https:\/\/gist.github.com\/7dac151410cf4b35ca9b49679f14eb53#file-gistfile1-txt",
            "permalink": "https:\/\/hyperledgerproject.slack.com\/files\/fbenhamo\/F3RD8M0FQ\/gistfile1_txt.txt",
            "edit_link": "https:\/\/hyperledgerproject.slack.com\/files\/fbenhamo\/F3RD8M0FQ\/gistfile1_txt.txt\/edit",
            "preview": "$ docker logs dev-jdoe-mycc-0-48baa00e355e6db1648cff44e28f1dbf322523a99ffe283fd99a00348466eb78075559488e372409bb691aab29cfa894645c9c2737781367012e0c816eb227b7\n2017\/01\/12 16:38:41 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = \"transport: dial tcp 0.0.0.0:7051: getsockopt: connection refused\"; Reconnecting to {\"0.0.0.0:7051\" <nil>}\n2017\/01\/12 16:38:42 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = \"transport: dial tcp 0.0.0.0:7051: getsockopt: connection refused\"; Reconnecting to {\"0.0.0.0:7051\" <nil>}\n16:38:43.317 [shim] ERRO : Error trying to connect to local peer: grpc: timed out when dialing\n2017\/01\/12 16:38:43 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = \"transport: dial tcp 0.0.0.0:7051: getsockopt: connection refused\"; Reconnecting to {\"0.0.0.0:7051\" <nil>}",
            "preview_highlight": "<div class=\"CodeMirror cm-s-default CodeMirrorServer\" oncopy=\"if(event.clipboardData){event.clipboardData.setData('text\/plain',window.getSelection().toString().replace(\/\\u200b\/g,''));event.preventDefault();event.stopPropagation();}\">\n<div class=\"CodeMirror-code\">\n<div><pre>$ docker logs dev-jdoe-mycc-0-48baa00e355e6db1648cff44e28f1dbf322523a99ffe283fd99a00348466eb78075559488e372409bb691aab29cfa894645c9c2737781367012e0c816eb227b7<\/pre><\/div>\n<div><pre>2017\/01\/12 16:38:41 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = &quot;transport: dial tcp 0.0.0.0:7051: getsockopt: connection refused&quot;; Reconnecting to {&quot;0.0.0.0:7051&quot; &lt;nil&gt;}<\/pre><\/div>\n<div><pre>2017\/01\/12 16:38:42 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = &quot;transport: dial tcp 0.0.0.0:7051: getsockopt: connection refused&quot;; Reconnecting to {&quot;0.0.0.0:7051&quot; &lt;nil&gt;}<\/pre><\/div>\n<div><pre>16:38:43.317 [shim] ERRO : Error trying to connect to local peer: grpc: timed out when dialing<\/pre><\/div>\n<div><pre>2017\/01\/12 16:38:43 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = &quot;transport: dial tcp 0.0.0.0:7051: getsockopt: connection refused&quot;; Reconnecting to {&quot;0.0.0.0:7051&quot; &lt;nil&gt;}<\/pre><\/div>\n<\/div>\n<\/div>\n",
            "lines": 6,
            "lines_more": 1,
            "preview_is_truncated": false,
            "channels": [
                "C0YQ1NHGD"
            ],
            "groups": [],
            "ims": [],
            "comments_count": 0
        },
        "user": "U3MB5BH42",
        "upload": false,
        "display_as_bot": false,
        "username": "<@U3MB5BH42|fbenhamo>",
        "bot_id": null,
        "ts": "1484322924.001052"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "I can get similar errors by forcing chaincode_example02 to connect to a wrong port for example",
        "edited": {
            "user": "U3MB5BH42",
            "ts": "1484323579.000000"
        },
        "ts": "1484322986.001055"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "like `CORE_PEER_ADDRESS=127.0.0.1:8051 CORE_CHAINCODE_ID_NAME=mycc .\/chaincode_example02`",
        "ts": "1484323010.001056"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "it looks like its trying to connect to 0.0.0.0",
        "ts": "1484323037.001057"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "yes",
        "ts": "1484323044.001058"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "but that's the default parameters",
        "ts": "1484323055.001059"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "and apparently that's equivalent to 127.0.0.1 for grpc",
        "ts": "1484323064.001060"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "right, but I dont think that is right",
        "ts": "1484323088.001061"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "this is when running the UTs?",
        "ts": "1484323097.001062"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "sorry, what do you mean by UT?",
        "ts": "1484323108.001063"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "unit-tests, sorry",
        "ts": "1484323113.001064"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "no, just trying the simple example",
        "ts": "1484323134.001065"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "here: <https:\/\/jira.hyperledger.org\/browse\/FAB-37>",
        "ts": "1484323138.001066"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "ah, ok, that is your problem",
        "ts": "1484323141.001067"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "(I think)",
        "ts": "1484323145.001068"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "try this",
        "ts": "1484323148.001069"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "take a look at .\/test\/docker-compose.yml",
        "ts": "1484323159.001070"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "in particular: CORE_PEER_ADDRESSAUTODETECT=true",
        "ts": "1484323172.001071"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "that instructs the peer to dynamically discover its IP",
        "ts": "1484323184.001072"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "you are running the peer in docker?",
        "ts": "1484323189.001073"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "no",
        "ts": "1484323195.001074"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "I'm running it manually on my computer",
        "ts": "1484323207.001075"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "so peer=native",
        "ts": "1484323209.001076"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "ok",
        "ts": "1484323210.001077"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "then just set that in the environment for the peer",
        "ts": "1484323229.001078"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "OSX docker is slightly different: 0.0.0.0 wont work like it does in Linux",
        "ts": "1484323247.001081"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "so, the defaults will work if the peer is running natively on linux, but not OSX",
        "ts": "1484323269.001082"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "OSX requires the AUTODETECT",
        "ts": "1484323275.001083"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "ok, I'm trying this",
        "ts": "1484323286.001084"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "what I expect to see is the chaincode will now be given a specific IP to connect to",
        "ts": "1484323311.001085"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "Ok, that gives exactly the same results as when I force CORE_PEER_ADDRESS to my wifi IP address",
        "ts": "1484323479.001086"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "deployment seems to work.",
        "ts": "1484323484.001087"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "but invoke then does not work.",
        "ts": "1484323489.001088"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "`Error: Error endorsing invoke: rpc error: code = 2 desc = failed to obtain cds for mycc - Error executing chaincode: Transaction returned with failure: transaction not found mycc\/**TEST_CHAINID**`",
        "ts": "1484323497.001089"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "```2017-01-13 11:04:16.690 EST [shim] func1 -&gt; ERRO 18e [6c5e5d4f]Transaction execution failed. Sending ERROR\n2017-01-13 11:04:16.690 EST [chaincode] processStream -&gt; DEBU 18f [6c5e5d4f]Received message ERROR from shim\n2017-01-13 11:04:16.690 EST [chaincode] processStream -&gt; ERRO 190 Got error: transaction not found mycc\/**TEST_CHAINID**```",
        "ts": "1484323513.001090"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "thats a different error",
        "ts": "1484326571.001094"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "i think you need to be running the orderer",
        "ts": "1484326578.001095"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "I get the error too, <@U0ULK2JPP> helped me to diagnose that the connection between peer\/orderer was broken",
        "ts": "1484326605.001096"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "i get the impression that in your setup, orderer isnt even started",
        "ts": "1484326617.001097"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "if that is the case, try \"make orderer &amp;&amp; .\/build\/bin\/orderer\" in another terminal",
        "ts": "1484326647.001098"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "I cleaned up everything and using either CORE_PEER_ADDRESSAUTODETECT and CORE_PEER_ADDRESS, ever",
        "ts": "1484326649.001099"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "Since I did a lot of tests, I guess I may have done something wrong.",
        "ts": "1484326670.001100"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "Thanks a lot.",
        "ts": "1484326672.001101"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "The simple example now works.",
        "ts": "1484326677.001102",
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "U0KPFAZNF"
                ],
                "count": 1
            }
        ]
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "np",
        "ts": "1484326678.001103"
    },
    {
        "type": "message",
        "user": "U3MB5BH42",
        "text": "I don't know if the unit tests work or not, but the simple example is sufficient for me",
        "ts": "1484326693.001104"
    },
    {
        "type": "message",
        "user": "U0KPFAZNF",
        "text": "cool",
        "ts": "1484326699.001105"
    },
    {
        "type": "message",
        "user": "U2TD4Q7NW",
        "text": "<@U0KPFAZNF>  <https:\/\/github.com\/jkilpatr\/fabric-baseimage-2.0>",
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "jkilpatr\/fabric-baseimage-2.0",
                "title_link": "https:\/\/github.com\/jkilpatr\/fabric-baseimage-2.0",
                "text": "fabric-baseimage-2.0 - An Ansible based build process for Fabric base image with platform agnostic design",
                "fallback": "GitHub: jkilpatr\/fabric-baseimage-2.0",
                "thumb_url": "https:\/\/avatars1.githubusercontent.com\/u\/19688153?v=3&s=400",
                "from_url": "https:\/\/github.com\/jkilpatr\/fabric-baseimage-2.0",
                "thumb_width": 327,
                "thumb_height": 327,
                "service_icon": "https:\/\/github.com\/apple-touch-icon.png",
                "id": 1
            }
        ],
        "ts": "1484343350.001134"
    },
    {
        "type": "message",
        "user": "U2TD4Q7NW",
        "text": "let me know what you think of the structure, I've got converged code (aka the same ansible playbook) running in a distro and arch agnostic manner, the bootstrap playbook handles kicking off different container builds in parallel, all at once for x86 stuff, going to need to borrow some arm hardware for better multiarch testing.",
        "ts": "1484343418.001136"
    },
    {
        "type": "message",
        "user": "U2TD4Q7NW",
        "text": "it's barebones for now, but I think porting all existing baseimage script functionality into this structure should come out neater.",
        "ts": "1484343457.001137"
    }
]